# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iLATVRXruOX3hjXSKWXFTe2Lrr04hyM-
"""

import re
from typing import Iterable, List

import spacy
from sklearn.base import BaseEstimator, TransformerMixin


nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])


class TextPreprocessor(BaseEstimator, TransformerMixin):
    """Text preprocessing used before TF-IDF + LinearSVC.

    Keep this class import path stable. The joblib model references this class
    when it is loaded by the FastAPI app.
    """

    def __init__(self, min_token_len: int = 2):
        self.min_token_len = min_token_len

    def fit(self, X: Iterable[str], y=None):
        return self

    def transform(self, X: Iterable[str]) -> List[str]:
        return [self.preprocess(text) for text in X]

    def preprocess(self, text: str) -> str:
        if not isinstance(text, str):
            text = ""

        text = text.lower()
        text = re.sub(r"http\S+|www\S+", " ", text)
        text = re.sub(r"\S+@\S+", " ", text)
        text = re.sub(r"<.*?>", " ", text)
        text = re.sub(r"\s+", " ", text).strip()

        doc = nlp(text)
        tokens = [
            token.lemma_
            for token in doc
            if token.is_alpha
            and not token.is_stop
            and not token.like_num
            and len(token.lemma_) >= self.min_token_len
        ]
        return " ".join(tokens)